@REM .PHONY: all clean

@REM all:
	@echo ......
	@echo 转换中...
	@echo 时间消耗可能很长...在当前命令执行完成前请不要退出...

	python ".\res\render_win.py"
	lyx -E pdf4 output.pdf .\example\main.lyx
	@echo 转换完毕...
@REM clean:
	@REM rd/s/q .\\build